### ISSUE TITLE
Write step-by-step tutorial based on MongoDb example code

### ISSUE THREAD

**Issue by robesz** [jaystack/odata-v4-server-mongodb-example#6]

**Comment by egarim** [comment]
Hi I can create the tutorial for you guys  i have been able to compile and test the project but not to run it. when i run the npm start command i got this
npm ERR! missing script: start

when I define the start command on the package.json i got this ouput

> odata-v4-server-mongodb-example@0.1.0 start C:\jdata
> node lib/js/server.js

no error or anything, but when I browse 

http://localhost:3000/

there is nothing running there, any idea of what I'm doing wrong? I'm able to see the data on the mongo server and the test works perfect

**Comment by lazarv** [comment]
Hi @egarim,
the missing npm start script is now available. It starts the TS version of the server on port 3000. Should be run now correctly on localhost.

**Comment by egarim** [comment]
Great, I will record a new tutorial for mongo as I did with postgres, here is the url for the postgress video tutorial if you want to watch it

 

https://youtu.be/Qu6sLanVqUs

**Comment by egarim** [comment]
Great, I will record a new tutorial for mongo as I did with postgres, here
is the url for the postgress video tutorial if you want to watch it



https://youtu.be/Qu6sLanVqUs



*From:* Viktor Lázár [mailto:notifications@github.com]
*Sent:* Tuesday, August 22, 2017 1:44 PM
*To:* jaystack/odata-v4-server-mongodb-example <odata-v4-server-mongodb-
example@noreply.github.com>
*Cc:* Jose Ojeda <joche.ojeda@bitframeworks.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [jaystack/odata-v4-server-mongodb-example] Write
step-by-step tutorial based on MongoDb example code (#6)



Hi @egarim <https://github.com/egarim>,
the missing npm start script is now available. It starts the TS version of
the server on port 3000. Should be run now correctly on localhost.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jaystack/odata-v4-server-mongodb-example/issues/6#issuecomment-323989194>,
or mute the thread
